name: Main testing workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install "tox~=4.0" tox-gh coverage[toml]
    - name: Type checking
      # Ignore errors for older pythons
      continue-on-error: ${{ contains(fromJSON('["3.7", "3.8", "3.9"]'), matrix.python-version)}}
      run: |
        tox -e mypy
    - name: Test with tox
      env:
        TOX_PARALLEL_NO_SPINNER: 1
      run: |
        coverage erase
        tox --parallel
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true # optional (default = false)
