name: Main testing workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            toxfactor: py37
            ignore-typecheck-outcome: true
            ignore-test-outcome: false
          - python-version: "3.8"
            toxfactor: py38
            ignore-typecheck-outcome: true
            ignore-test-outcome: false
          - python-version: "3.9"
            toxfactor: py39
            ignore-typecheck-outcome: true
            ignore-test-outcome: false
          - python-version: "3.10"
            toxfactor: py310
            ignore-typecheck-outcome: true
            ignore-test-outcome: false
          - python-version: "3.11"
            toxfactor: py311
            ignore-typecheck-outcome: true
            ignore-test-outcome: false
          - python-version: "3.12.0-alpha.3"
            toxfactor: py312
            ignore-typecheck-outcome: true
            ignore-test-outcome: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install "tox~=4.0" coverage[toml]
    - name: Type checking
      # Ignore errors for older pythons
      continue-on-error: ${{ matrix.ignore-typecheck-outcome }}
      run: |
        tox -e ${{ matrix.toxfactor }}-mypy
    - name: Test with tox
      continue-on-error: ${{ matrix.ignore-test-outcome }}
      run: |
        coverage erase
        tox run-parallel -f ${{ matrix.toxfactor }} --parallel-no-spinner --parallel-live
        coverage combine
        coverage xml
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true # optional (default = false)
